version: '2'

services:
  php:
    image: php:fpm
    volumes:
      - ${SYMFONY_PROJECT_ROOT}/:/var/www/project
  web:
    image: nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
    links:
      - php