version: '2'

services:
  php:
    build: docker/php
    volumes:
      - ${SYMFONY_PROJECT_ROOT}/:/var/www/project
    links:
      - db
  web:
    image: nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
